export const seu_buffet = {
  name: "Seu Buffet",
  user: "seu_buffet",
  social: {
    facebook: "seu_buffet",
    instagram: "seu_buffet",
    whatsapp: "5527998830843",
  },
  description:
    "Sua bio vai aqui. Opcionalmente, descreva os serviços que seu buffet realiza e informe para seu cliente fazer o orçamento abaixo... As imagens daqui são apenas exemplos, você pode escolher suas imagens.",
  logo: "/seu_buffet/logo.jpg",
  services: [
    {
      name: "Roda de Boteco",
      image: "/seu_buffet/rodadebuteco.jpg",
      items: [
        "Filé de peito de frango empanado",
        "Batata frita",
        "Polenta frita",
        "Tilápia frita",
        "Linguiça churrasco",
        "Linguiça caseira",
        "Torresmo",
        "Mandioquita",
        "Costelinha de porco",
        "Banana frita",
        "Barquete",
        "Torradas com antepasto e patês variados",
        "Batata baby",
        "Mini hambúrguer",
        "Mini cachorro quente",
        "Mini churros",
        "Mini pizza",
        "Ovo de codorna",
        "Anel de cebola",
        "Salgadinhos",
        "Tábua de frios (lombo, salaminho, presunto, queijos variados, azeitona, etc.)",
      ],
    },
    {
      name: "Jantar",
      image: "/seu_buffet/jantar.jpg",
      items: [
        "Arroz",
        "Feijão tropeiro",
        "Boi ao molho madeira",
        "Frango",
        "Carne de porco assada",
        "Strogonoff de frango ou boi",
        "Salada com folhas, frutas e verduras",
        "Farofas",
        "Maionese",
        "Salpicão",
        "Tilápia",
        "Batata Alemã",
        "Chucrute",
        "Vinagrete",
        "Salsichão",
        "Joelho de porco",
      ],
    },
    {
      name: "Almoço",
      image: "/seu_buffet/almoco.jpg",
      items: [
        "Arroz",
        "Feijão tropeiro",
        "Boi ao molho madeira",
        "Frango",
        "Carne de porco assada",
        "Strogonoff de frango ou boi",
        "Salada com folhas, frutas e verduras",
        "Farofas",
        "Maionese",
        "Salpicão",
        "Tilápia",
        "Batata Alemã",
        "Chucrute",
        "Vinagrete",
        "Salsichão",
        "Joelho de porco",
      ],
    },
    {
      name: "Churrasco",
      image: "/seu_buffet/churrasco.jpg",
      items: [
        "Carne de boi (Chorizo, Contrafilé, Alcatra ou Picanha)",
        "Carne de porco",
        "Carne de frango",
        "Linguiça",
        "Pão de alho",
        "Queijo",
        "Vinagrete",
        "Feijão tropeiro",
      ],
    },
    {
      name: "Coffee Break",
      image: "/seu_buffet/coffeebreak.jpg",
      items: [
        "Cafés (c/ açúcar e sem açúcar)",
        "Leite",
        "Bolos (Laranja, cenoura, chocolate, fubá, mesclado, aipim, coco ou cuca alemão)",
        "Pães (caseiro, sal, broto de milho ou doce)",
        "Cachorro quente",
        "Mini Hambúrguer",
        "Pão de queijo",
        "Torradas",
        "Biscoitos",
        "Patês",
        "Queijos (Chimia ou minas)",
        "Presunto e queijo",
        "Salgadinhos",
        "Doces (Goiaba, mamão ou mamão com laranja",
        "Frutas (Banana, melão, melancia ou mamão)",
      ],
    },
    {
      name: "Bebidas",
      image: "/seu_buffet/bebidas.jpg",
      items: [
        "Suco natural 2 sabores",
        "Coca-cola",
        "Guaraná",
        "Cerveja (Brahma, Skol, Amstel)",
        "Chopp",
        "Drinks (Alcoólico ou não alcoólico)",
        "Coquetel de frutas",
      ],
    },
  ],
};
